# fly.toml app configuration file generated for codebase-curator on 2023-10-11T00:44:28-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "codebase-curator"
primary_region = "ord"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
